export const ACTIONS_FILTERS = {
   // Tags
   TOGGLE_TAG: 'TOGGLE_TAG',
   RESET_TAGS: 'RESET_TAGS',
   SET_TAG_ANDOR: 'SET_TAG_ANDOR',
   // Card Types
   TOGGLE_CARD_TYPE: 'TOGGLE_CARD_TYPE',
   // Cost
   SET_COST: 'SET_COST',
   SET_COST_MINMAXEQUAL: 'SET_COST_MINMAXEQUAL',
   // Search
   SET_SEARCHVALUE: 'SET_SEARCHVALUE',
   // Production
   TOGGLE_PRODUCTION: 'TOGGLE_PRODUCTION',
   RESET_PRODUCTION: 'RESET_PRODUCTION',
   SET_PRODUCTION_ANDOR: 'SET_PRODUCTION_ANDOR',
   // VP
   TOGGLE_VP: 'SET_VP',
   SET_VP_NEGALLPOS: 'SET_VP_NEGALLPOS',
   // Requirements
   TOGGLE_REQ: 'TOGGLE_REQ',
   RESET_REQS: 'RESET_REQS',
   SET_REQ_ANDOR: 'SET_REQ_ANDOR',
   // Parameters
   TOGGLE_PARAMETER: 'TOGGLE_PARAMETER',
   RESET_PARAMETERS: 'RESET_PARAMETERS',
   SET_PARAMETERS_ANDOR: 'SET_PARAMETERS_ANDOR',
   // Can Have Units
   TOGGLE_UNIT: 'TOGGLE_UNIT',
   RESET_UNITS: 'RESET_UNITS',
   // Reset All
   RESET_ALL: 'RESET_ALL',
}